name: GitHub Actions Demo
run-name: CI/CD for test DevOps task

on: [push]

env:
  NAMESPACE: testtask

jobs:

  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login docker
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run x86 build
        run: docker build ./api/  -t tapi:x86_64${{ github.sha }}
      - run: docker build ./front/  -t front:x86_64${{ github.sha }}

      - name: Run arm push 
        run: docker buildx build --platform linux/arm64 ./api/ -t ghcr.io/$NAMESPACE/tapi:arm64${{ github.sha }} --push
      - run: docker buildx build --platform linux/arm64 ./front/  -t ghcr.io/$NAMESPACE/front:arm64${{ github.sha }} --push

      - run: docker push ghcr.io/$NAMESPACE/tapi:x86_64${{ github.sha }}
      - run: docker push ghcr.io/$NAMESPACE/front:x86_64${{ github.sha }}

